# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:latest AS build

WORKDIR /app

COPY . .

RUN go mod tidy

RUN go build -o /app/course main.go

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build /app/course /app/course

EXPOSE 1234

USER nonroot:nonroot

ENTRYPOINT ["/app/course"]